version: "3"
services:
  db:
    image: mysql:5.6
    container_name: mysql_knu
    ports:
      - "3306:3306" #
    environment: 
      MYSQL_ROOT_PASSWORD: "knuapp"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ubuntu/mysql:/var/lib/mysql