version: "3"
services:
  kangwonapitest:
    image: kangwon-spring:0.2
    build: .
    ports:
      - 8080:8080
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf